// Herd Mentality question bank — curated for a Delhi / India journaling-group community.
// Goal: questions the herd can actually converge on, fun, decent, no alcohol.
// Best answers are short. Mix of: shared-culture, desi, Delhi, the-group, reflective, silly.
export const QUESTIONS = [
  // --- Bollywood & screen (shared, high-converge) ---
  "Name a Shah Rukh Khan movie",
  "Name a Bollywood actor everyone's mom loves",
  "Name a Bollywood villain",
  "Name a 90s Bollywood song everyone knows",
  "Name a Bollywood dialogue everyone can finish",
  "Name a recent web series you binged",
  "Name a Bollywood dance step everyone attempts",
  "Name a Bollywood movie you've watched more than 5 times",
  "Name a cartoon you watched as a kid",
  "Name a TV serial your family watched at dinner",
  "Name an item song everyone knows the steps to",
  "Name a Bollywood couple",

  // --- Cricket & sport (shared) ---
  "Name a famous Indian cricketer",
  "Name an IPL team",
  "Name a cricket shot",
  "Name a sport you played in school",
  "Name a game you played in the gully",
  "Name a sport India should be better at",

  // --- Desi food (very high-converge, fun) ---
  "Name a street food you'd eat every day if you could",
  "Name a chaat",
  "Name a samosa's best partner",
  "Name a filling for a paratha",
  "Name an Indian sweet at every festival",
  "Name a dish you order at a dhaba",
  "Name a South Indian dish",
  "Name something you add to Maggi",
  "Name a snack for a rainy Delhi evening",
  "Name a biryani topping people fight over",
  "Name a thing in every Indian fridge",
  "Name a pickle (achaar) flavour",
  "Name what you dip a pakora in",
  "Name a roadside drink for Delhi summer",
  "Name a wedding-buffet dish everyone rushes to",
  "Name a comfort food when you're sad",
  "Name a thing aunties pack in a tiffin",
  "Name a chai-time snack",
  "Name a dessert at a birthday",
  "Name a fruit best in summer",
  "Name a thing you eat with your hands",
  "Name a midnight snack",

  // --- Chai / coffee / daily ---
  "Chai or coffee?",
  "Name a place to get good momos in Delhi",
  "Name a thing that makes chai perfect",
  "Name the best time of day for chai",


  // --- Festivals & family ---
  "Name a festival you look forward to",
  "Name a thing you do on Diwali",
  "Name a Holi colour",
  "Name a thing that happens at every Indian wedding",
  "Name a question every relative asks you",
  "Name a thing your mom keeps 'for guests'",
  "Name a sound of an Indian morning",
  "Name a chore your parents nag you about",
  "Name a game played at family gatherings",

  // --- The group (community bonding — gold) ---
  "Who in this group is always late?",
  "Who in this group journals most regularly?",
  "Who here gives the best advice?",
  "Who would survive a Delhi power cut the longest?",
  "Who in this group could write a bestselling memoir?",
  "Who's most likely to go off-grid for a month?",
  "Who talks the most in this group?",
  "Who's the unofficial parent of this group?",
  "Who here would win a debate?",
  "Who's most likely to become famous?",
  "Who would survive longest on a deserted island?",
  "Who's the most competitive person here?",
  "Who's most likely to plan the next trip?",
  "Who would forget their own birthday?",
  "Who here has the most screenshots saved?",

  // --- Journaling / reflective (community-fit, still convergeable) ---
  "Name the best time of day to journal",
  "Name a small thing that makes a good day",
  "Name a habit worth building",
  "Name a thing you're grateful for today",
  "Name a feeling that's hard to put into words",
  "Name a reason people start journaling",
  "Name the best way to unwind after a long day",
  "Name a thing that ruins your morning",
  "Name a thing on everyone's bucket list",
  "Name a comfort show to rewatch",
  "Name a thing that instantly lifts your mood",
  "Name something you wish you did more often",
  "Name a distraction you reach for too easily",
  "Name a thing worth waking up early for",
  "Name a goal everyone sets but rarely keeps",

  // --- Universal 'name a...' (reliable converge) ---
  "Name a colour of the rainbow",
  "Name a yellow fruit",
  "Name a green vegetable",
  "Name an animal with a tail",
  "Name a zoo animal",
  "Name a farm animal",
  "Name a bird",
  "Name a sea creature",
  "Name a flower",
  "Name a tree you'd find in Delhi",
  "Name a part of the body",
  "Name a piece of clothing",
  "Name a shape",
  "Name a planet",
  "Name a season",
  "Name a month",
  "Name a day of the week",
  "Name a musical instrument",
  "Name a kitchen appliance",
  "Name a type of weather",
  "Name a mode of transport in Delhi",
  "Name a language spoken in India",
  "Name a school subject",
  "Name a job kids say they want",
  "Name a board game",
  "Name a card game",
  "Name a social media app you open first",
  "Name an app you check too often",
  "Name a streaming service",
  "Name a phone brand",
  "Name a colour for a car",

  // --- Opinions & favourites (fun spread) ---
  "What's the best pizza topping?",
  "What's the worst pizza topping?",
  "What's the best ice cream flavour?",
  "What's the best superpower to have?",
  "What's the most useless superpower?",
  "What's the best subject in school?",
  "What's the most overrated movie?",
  "What's the best emoji?",
  "What's the best day of the week?",
  "What's the worst household chore?",
  "What's the best smell in the world?",
  "What's the most annoying sound?",
  "What's the best way to spend a Sunday?",
  "What's the best thing about monsoon?",
  "What's the worst thing about Delhi summer?",
  "What's the best comfort food?",
  "What's an animal that would make a terrible roommate?",
  "What's the best excuse for not replying to texts?",
  "What's the most overrated trend?",
  "What's the best thing about weekends?",

  // --- 'Name something...' prompts (silly, decent) ---
  "Name something you do before bed",
  "Name something you do when you're bored",
  "Name something you keep in your bag",
  "Name something everyone loses constantly",
  "Name something that's better at night",
  "Name something you'd take to a deserted island",
  "Name something people pretend to like",
  "Name something cold",
  "Name something round",
  "Name something that flies",
  "Name something with wheels",
  "Name something people are scared of",
  "Name something you do only on holidays",
  "Name something you'd never share",
  "Name a way to get rich quick",
  "Name a reason to skip a Monday",
  "Name a thing that always runs out too fast",

  // --- Dark comedy (morbid + funny, varied phrasing, still convergeable) ---
  "What's a terrible thing to say at a funeral?",
  "What's the worst-possible last meal?",
  "Where's the worst place to faint?",
  "What's a lie everyone tells the doctor?",
  "What would you regret buying on EMI?",
  "What's the worst gift to give at a wedding?",
  "Who's the worst person to be stuck in a lift with?",
  "When's the worst time for your phone to die?",
  "What's a terrible excuse for missing a funeral?",
  "What would you want buried with you?",
  "What's a terrible name for a hospital?",
  "What's the worst thing to find in your biryani?",
  "What always dies at the worst possible moment?",
  "What's the worst job for a clumsy person?",
  "What's a terrible theme for a birthday party?",
  "When's the worst time to start laughing?",
  "What would you fake your death to avoid?",
  "Which pet is a terrible idea in a small Delhi flat?",
  "What's the worst thing to forget on your wedding day?",
  "What's the worst song to play at a funeral?",
  "What always ruins a group photo?",
  "Where's the worst place to lose your wallet?",
  "What's a doomed new year resolution?",
  "When's the worst time to run out of toilet paper?",
  "Which is the worst seat on a long flight?",
  "What does nobody admit they Google?",
  "What's the worst nickname to be stuck with?",
  "What's a terrible excuse for being late to your own wedding?",
  "What's the worst thing to whisper in the dark?",
  "What's a terrible gift for a newborn?",
  "Where's the worst place to get a call from your boss?",
  "What always breaks right after the warranty ends?",
  "When's the worst time to sneeze?",
  "What's a terrible password everyone has used?",
  "What's the worst roommate habit?",
  "What should you never say to a traffic cop?",
  "Where's the worst place to get hiccups?",
  "What would you hate to inherit?",
  "What's the worst reason to become famous?",
  "What's a terrible thing to be allergic to?",
  "When's the worst time for the WiFi to die?",
  "What's the worst thing to find in the office fridge?",
  "How's the worst way to find out you're fired?",
  "What still haunts you from your school days?",
  "What's the worst way to break up with someone?",
  "Who's the worst plus-one for a date?",
  "What's a slow death disguised as a family function?",
  "What's the worst superpower to have at a funeral?",
  "What's the worst flavour of ice cream?",
  "What's the worst job to be doing at 3am?",
];
