// Herd Mentality question bank — India-flavoured, fun, opinion-style (answers not obvious).
// Schema: flat array of { category, question }. Add per-question fields later (difficulty, tags…)
// without restructuring. CATEGORIES is derived for filtering / future category UI.
// Curated for quality: keep convergent opinion-style questions (a herd can form);
// drop personal/autobiographical, open-ended "what would you do", bland, and duplicates.
export const QUESTIONS = [
  // ===== Bollywood & Screen =====
  { category: "Bollywood & Screen", question: "What's a Bollywood cliché that needs to die?" },
  { category: "Bollywood & Screen", question: "What's the worst dance step to attempt at a sangeet?" },
  { category: "Bollywood & Screen", question: "Which actor could read a grocery list and you'd still watch?" },
  { category: "Bollywood & Screen", question: "What's the most unrealistic thing Bollywood heroes do?" },
  { category: "Bollywood & Screen", question: "Which song is impossible not to dance to at a wedding?" },
  { category: "Bollywood & Screen", question: "What's the most quotable Bollywood dialogue?" },
  { category: "Bollywood & Screen", question: "What's the worst item song to play in front of family?" },
  { category: "Bollywood & Screen", question: "What's a TV serial that went on way too long?" },
  { category: "Bollywood & Screen", question: "Which actor always plays the exact same role?" },
  { category: "Bollywood & Screen", question: "What's a movie everyone pretends to understand?" },
  { category: "Bollywood & Screen", question: "Which song would you ban at weddings forever?" },
  { category: "Bollywood & Screen", question: "Who's the most overrated Bollywood actor?" },

  // ===== Embarrassing & Cringe =====
  { category: "Embarrassing & Cringe", question: "What's a cringe thing everyone did as a teenager?" },
  { category: "Embarrassing & Cringe", question: "What's the worst text to send to the wrong person?" },
  { category: "Embarrassing & Cringe", question: "What's the most awkward way to run into your ex?" },
  { category: "Embarrassing & Cringe", question: "What's the worst place to trip and fall?" },
  { category: "Embarrassing & Cringe", question: "What's the cringiest thing to shout in public?" },
  { category: "Embarrassing & Cringe", question: "What's the worst time to get caught talking to yourself?" },
  { category: "Embarrassing & Cringe", question: "What's an embarrassing thing parents do in public?" },
  { category: "Embarrassing & Cringe", question: "What's the most awkward thing to happen in a meeting?" },
  { category: "Embarrassing & Cringe", question: "What's the worst thing to call a teacher by accident?" },
  { category: "Embarrassing & Cringe", question: "What's the most awkward lift moment?" },
  { category: "Embarrassing & Cringe", question: "Who's the worst person to forget the name of?" },
  { category: "Embarrassing & Cringe", question: "What's the cringiest type of social media post?" },
  { category: "Embarrassing & Cringe", question: "What's the most awkward thing to do on a first date?" },
  { category: "Embarrassing & Cringe", question: "What's the worst time for your stomach to growl loudly?" },
  { category: "Embarrassing & Cringe", question: "What's the cringiest pickup line you've heard?" },
  { category: "Embarrassing & Cringe", question: "What's an embarrassing thing in everyone's photo gallery?" },
  { category: "Embarrassing & Cringe", question: "What's the most awkward family WhatsApp group moment?" },
  { category: "Embarrassing & Cringe", question: "What's a thing you pretend to understand but don't?" },
  { category: "Embarrassing & Cringe", question: "What's the worst place to get the giggles?" },
  { category: "Embarrassing & Cringe", question: "What's a phase everyone's embarrassed they had?" },
  { category: "Embarrassing & Cringe", question: "What's the worst time to realise you have food in your teeth?" },
  { category: "Embarrassing & Cringe", question: "What's the cringiest abbreviation people text?" },

  // ===== Family & Relatives =====
  { category: "Family & Relatives", question: "What's the most annoying question relatives always ask?" },
  { category: "Family & Relatives", question: "What's a thing every mom keeps 'for guests'?" },
  { category: "Family & Relatives", question: "What's the worst comparison relatives make?" },
  { category: "Family & Relatives", question: "What's a thing every dad does with the fan or AC?" },
  { category: "Family & Relatives", question: "What's a thing relatives judge you for instantly?" },
  { category: "Family & Relatives", question: "What's the most overused parental threat?" },
  { category: "Family & Relatives", question: "What's a thing every household hoards forever?" },
  { category: "Family & Relatives", question: "What's the most awkward dinner-table topic?" },
  { category: "Family & Relatives", question: "What's the most unrealistic expectation parents have?" },
  { category: "Family & Relatives", question: "What's a thing every family WhatsApp group sends daily?" },
  { category: "Family & Relatives", question: "What's a thing your mom blames for everything?" },
  { category: "Family & Relatives", question: "What's a thing every grandparent says?" },
  { category: "Family & Relatives", question: "What's the worst 'log kya kahenge' moment?" },
  { category: "Family & Relatives", question: "What's the worst thing to admit to your parents?" },
  { category: "Family & Relatives", question: "What's a thing parents do with leftover food?" },
  { category: "Family & Relatives", question: "What's a thing every dad is weirdly proud of?" },
  { category: "Family & Relatives", question: "What's a thing parents say about your sleep schedule?" },
  { category: "Family & Relatives", question: "What's the worst thing to interrupt your dad's nap for?" },

  // ===== Food & Cravings =====
  { category: "Food & Cravings", question: "What's the most overrated street food?" },
  { category: "Food & Cravings", question: "What's a food combo that sounds gross but works?" },
  { category: "Food & Cravings", question: "What's the worst pizza topping?" },
  { category: "Food & Cravings", question: "What's the worst thing to put in Maggi?" },
  { category: "Food & Cravings", question: "What's the most disappointing mithai?" },
  { category: "Food & Cravings", question: "What's the worst thing to order on a first date?" },
  { category: "Food & Cravings", question: "What's the most pointless 'healthy' food?" },
  { category: "Food & Cravings", question: "What's the most overrated cuisine?" },
  { category: "Food & Cravings", question: "What's the most disappointing birthday cake flavour?" },
  { category: "Food & Cravings", question: "What's the worst thing to bring to a potluck?" },
  { category: "Food & Cravings", question: "What's the worst leftover to reheat?" },
  { category: "Food & Cravings", question: "What's a food worth the bad breath?" },
  { category: "Food & Cravings", question: "What's the worst thing to microwave in an office?" },
  { category: "Food & Cravings", question: "What's a food that smells better than it tastes?" },
  { category: "Food & Cravings", question: "What's the most overrated viral food?" },
  { category: "Food & Cravings", question: "What's a food you pretend to like to be polite?" },

  // ===== Dating & Relationships =====
  { category: "Dating & Relationships", question: "What's the biggest red flag on a first date?" },
  { category: "Dating & Relationships", question: "What's the most overrated romantic gesture?" },
  { category: "Dating & Relationships", question: "What's the worst pet name for a partner?" },
  { category: "Dating & Relationships", question: "What's a dealbreaker that's secretly petty?" },
  { category: "Dating & Relationships", question: "What's a terrible idea for a first date?" },
  { category: "Dating & Relationships", question: "What's a lie everyone tells on dating apps?" },
  { category: "Dating & Relationships", question: "What's the cringiest way to slide into DMs?" },
  { category: "Dating & Relationships", question: "What's the worst time to say 'I love you'?" },
  { category: "Dating & Relationships", question: "What's the most awkward 'meet the parents' moment?" },
  { category: "Dating & Relationships", question: "What's a romantic trope that's actually creepy?" },
  { category: "Dating & Relationships", question: "What's the worst place to propose?" },
  { category: "Dating & Relationships", question: "What's a thing couples fight about that's so dumb?" },
  { category: "Dating & Relationships", question: "What's the cringiest thing couples do in public?" },
  { category: "Dating & Relationships", question: "What's a thing everyone does after a breakup?" },
  { category: "Dating & Relationships", question: "What's the worst thing to find on a partner's phone?" },
  { category: "Dating & Relationships", question: "What's a thing long-term couples stop pretending about?" },
  { category: "Dating & Relationships", question: "What's a thing that kills the mood instantly?" },
  { category: "Dating & Relationships", question: "What's the worst reason to stay with someone?" },
  { category: "Dating & Relationships", question: "What's the worst thing for a partner to be bad at?" },

  // ===== Money, Work & Adulting =====
  { category: "Money, Work & Adulting", question: "What's the worst thing to blow your salary on?" },
  { category: "Money, Work & Adulting", question: "What's a job that sounds fun but would be hell?" },
  { category: "Money, Work & Adulting", question: "What's the worst excuse for being late to work?" },
  { category: "Money, Work & Adulting", question: "What's the worst boss habit?" },
  { category: "Money, Work & Adulting", question: "What's a thing adults waste money on?" },
  { category: "Money, Work & Adulting", question: "What's the worst way to quit a job?" },
  { category: "Money, Work & Adulting", question: "What's the most annoying type of coworker?" },
  { category: "Money, Work & Adulting", question: "What's an adult task nobody warns you about?" },
  { category: "Money, Work & Adulting", question: "What's the worst thing to say in a job interview?" },
  { category: "Money, Work & Adulting", question: "What's a subscription everyone forgets they pay for?" },
  { category: "Money, Work & Adulting", question: "What's a thing that's a rip-off but we all pay for?" },
  { category: "Money, Work & Adulting", question: "What's an adulting skill everyone fakes?" },
  { category: "Money, Work & Adulting", question: "What's the most cringe LinkedIn post?" },
  { category: "Money, Work & Adulting", question: "What's a chore you'd happily pay to never do?" },
  { category: "Money, Work & Adulting", question: "What's a thing everyone exaggerates on their resume?" },
  { category: "Money, Work & Adulting", question: "What's the worst commute situation?" },
  { category: "Money, Work & Adulting", question: "What's the worst thing to say to your landlord?" },
  { category: "Money, Work & Adulting", question: "What's an overrated status symbol?" },
  { category: "Money, Work & Adulting", question: "What's a thing nobody admits they can't afford?" },

  // ===== Hypotheticals & Superpowers =====
  { category: "Hypotheticals & Superpowers", question: "What superpower would be useless in real life?" },
  { category: "Hypotheticals & Superpowers", question: "What animal would make the worst pet?" },
  { category: "Hypotheticals & Superpowers", question: "What would you ban if you ruled the world for a day?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst place to be teleported randomly?" },
  { category: "Hypotheticals & Superpowers", question: "If animals could talk, which would be the rudest?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst thing to be reincarnated as?" },
  { category: "Hypotheticals & Superpowers", question: "If you had a clone, what chore would you dump on it?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst place to have super hearing?" },
  { category: "Hypotheticals & Superpowers", question: "What's the most pointless thing to be world champion at?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst animal to be the size of a dog?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst superpower to have on a date?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst talent to go viral for?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst superhero name?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst superpower to give a toddler?" },

  // ===== Dark Comedy =====
  { category: "Dark Comedy", question: "What's a terrible thing to say at a funeral?" },
  { category: "Dark Comedy", question: "Where's the worst place to faint?" },
  { category: "Dark Comedy", question: "What's a lie everyone tells the doctor?" },
  { category: "Dark Comedy", question: "What's the worst gift to give at a wedding?" },
  { category: "Dark Comedy", question: "Who's the worst person to be stuck in a lift with?" },
  { category: "Dark Comedy", question: "When's the worst time for your phone to die?" },
  { category: "Dark Comedy", question: "What's a terrible name for a hospital?" },
  { category: "Dark Comedy", question: "What's the worst job for a clumsy person?" },
  { category: "Dark Comedy", question: "Which pet is a terrible idea in a small flat?" },
  { category: "Dark Comedy", question: "What's the worst thing to forget on your wedding day?" },
  { category: "Dark Comedy", question: "What always ruins a group photo?" },
  { category: "Dark Comedy", question: "Where's the worst place to lose your wallet?" },
  { category: "Dark Comedy", question: "What's a doomed new year resolution?" },
  { category: "Dark Comedy", question: "When's the worst time to run out of toilet paper?" },
  { category: "Dark Comedy", question: "Which is the worst seat on a long flight?" },
  { category: "Dark Comedy", question: "What always breaks right after the warranty ends?" },
  { category: "Dark Comedy", question: "What's a terrible password everyone has used?" },
  { category: "Dark Comedy", question: "What's the worst roommate habit?" },
  { category: "Dark Comedy", question: "What should you never say to a traffic cop?" },
  { category: "Dark Comedy", question: "What's a terrible thing to be allergic to?" },
  { category: "Dark Comedy", question: "When's the worst time for the WiFi to die?" },
  { category: "Dark Comedy", question: "What's the worst thing to find in the office fridge?" },
  { category: "Dark Comedy", question: "What's the worst way to find out you're fired?" },
  { category: "Dark Comedy", question: "What's the worst way to break up with someone?" },
  { category: "Dark Comedy", question: "What's a slow death disguised as a family function?" },

  // ===== The Group =====
  { category: "The Group", question: "Who in this group is always late?" },
  { category: "The Group", question: "Who'd survive longest on a deserted island?" },
  { category: "The Group", question: "Who talks the most in this group?" },
  { category: "The Group", question: "Who's the unofficial parent of this group?" },
  { category: "The Group", question: "Who'd win a debate about literally anything?" },
  { category: "The Group", question: "Who's most likely to become famous?" },
  { category: "The Group", question: "Who's most likely to plan the next trip?" },
  { category: "The Group", question: "Who's most likely to cry at a movie?" },
  { category: "The Group", question: "Who's the worst at replying to texts?" },
  { category: "The Group", question: "Who'd accidentally join a cult?" },
  { category: "The Group", question: "Who takes the most selfies?" },
  { category: "The Group", question: "Who'd spend their whole salary in a day?" },
  { category: "The Group", question: "Who's the most dramatic?" },
  { category: "The Group", question: "Who'd get lost in their own neighbourhood?" },
  { category: "The Group", question: "Who's most likely to ghost the group chat?" },
];

// Unique category list, in first-seen order — handy for a future category filter / picker.
export const CATEGORIES = [...new Set(QUESTIONS.map((q) => q.category))];
