// Herd Mentality question bank — India-flavoured, fun, opinion-style (answers not obvious).
// Schema: flat array of { category, question }. Add per-question fields later (difficulty, tags…)
// without restructuring. CATEGORIES is derived for filtering / future category UI.
export const QUESTIONS = [
  // ===== Bollywood & Screen =====
  { category: "Bollywood & Screen", question: "What's the most overrated Bollywood movie?" },
  { category: "Bollywood & Screen", question: "Which Bollywood movie have you secretly watched 10 times?" },
  { category: "Bollywood & Screen", question: "What's a Bollywood cliché that needs to die?" },
  { category: "Bollywood & Screen", question: "Which Bollywood villain was lowkey right?" },
  { category: "Bollywood & Screen", question: "What's the worst dance step to attempt at a sangeet?" },
  { category: "Bollywood & Screen", question: "Which movie makes you cry every single time?" },
  { category: "Bollywood & Screen", question: "What's a movie everyone loves but you find boring?" },
  { category: "Bollywood & Screen", question: "Which actor could read a grocery list and you'd still watch?" },
  { category: "Bollywood & Screen", question: "What's the most unrealistic thing Bollywood heroes do?" },
  { category: "Bollywood & Screen", question: "Which song is impossible not to dance to at a wedding?" },
  { category: "Bollywood & Screen", question: "What's a sequel that should never have been made?" },
  { category: "Bollywood & Screen", question: "Which Bollywood character would be a nightmare to date?" },
  { category: "Bollywood & Screen", question: "What's the most quotable Bollywood dialogue?" },
  { category: "Bollywood & Screen", question: "Which villain had the best wardrobe?" },
  { category: "Bollywood & Screen", question: "What's a plot twist that fooled everyone?" },
  { category: "Bollywood & Screen", question: "Which celebrity would you trust to plan your wedding?" },
  { category: "Bollywood & Screen", question: "What's the worst item song to play in front of family?" },
  { category: "Bollywood & Screen", question: "Which web series did everyone overhype?" },
  { category: "Bollywood & Screen", question: "What's a TV serial that went on way too long?" },
  { category: "Bollywood & Screen", question: "Which actor always plays the exact same role?" },
  { category: "Bollywood & Screen", question: "What's the most rewatchable comedy?" },
  { category: "Bollywood & Screen", question: "Which 90s song instantly takes you back to childhood?" },
  { category: "Bollywood & Screen", question: "Which Bollywood couple was clearly never going to last?" },
  { category: "Bollywood & Screen", question: "What's the cheesiest romantic gesture in any film?" },
  { category: "Bollywood & Screen", question: "Which movie scared you as a kid?" },
  { category: "Bollywood & Screen", question: "What's a remake nobody asked for?" },
  { category: "Bollywood & Screen", question: "What's the most satisfying movie revenge?" },
  { category: "Bollywood & Screen", question: "Which character death wrecked you?" },
  { category: "Bollywood & Screen", question: "What's a movie that's only good with snacks at 2am?" },
  { category: "Bollywood & Screen", question: "Which celebrity feud do you secretly follow?" },
  { category: "Bollywood & Screen", question: "What's the worst accent in a Bollywood movie?" },
  { category: "Bollywood & Screen", question: "Which fictional world would you actually move to?" },
  { category: "Bollywood & Screen", question: "What's a movie everyone pretends to understand?" },
  { category: "Bollywood & Screen", question: "Which song do you only know the chorus of?" },
  { category: "Bollywood & Screen", question: "What's the most unnecessary 3-hour movie?" },
  { category: "Bollywood & Screen", question: "Which reality show is your guilty pleasure?" },
  { category: "Bollywood & Screen", question: "What's a scene you always skip?" },
  { category: "Bollywood & Screen", question: "Which sidekick deserved their own movie?" },
  { category: "Bollywood & Screen", question: "What's the worst movie you've seen in a theatre?" },
  { category: "Bollywood & Screen", question: "Which celebrity seems like they'd be fun at a party?" },
  { category: "Bollywood & Screen", question: "What's the most overused Bollywood trope?" },
  { category: "Bollywood & Screen", question: "Which song would you ban at weddings forever?" },
  { category: "Bollywood & Screen", question: "What's a childhood cartoon that doesn't hold up?" },
  { category: "Bollywood & Screen", question: "Which movie do you quote way too often?" },
  { category: "Bollywood & Screen", question: "Who's the most overrated Bollywood actor?" },
  { category: "Bollywood & Screen", question: "Which movie has the best soundtrack?" },
  { category: "Bollywood & Screen", question: "What's the cringiest on-screen romance?" },
  { category: "Bollywood & Screen", question: "Which actor is overdue for a National Award?" },
  { category: "Bollywood & Screen", question: "What's a film that's better than the book?" },
  { category: "Bollywood & Screen", question: "Which dialogue can the whole family finish together?" },

  // ===== Embarrassing & Cringe =====
  { category: "Embarrassing & Cringe", question: "What's the most embarrassing thing in your search history?" },
  { category: "Embarrassing & Cringe", question: "What's a cringe thing everyone did as a teenager?" },
  { category: "Embarrassing & Cringe", question: "What's the worst text to send to the wrong person?" },
  { category: "Embarrassing & Cringe", question: "What's an embarrassing song stuck on your playlist?" },
  { category: "Embarrassing & Cringe", question: "What's the most awkward way to run into your ex?" },
  { category: "Embarrassing & Cringe", question: "What's a lie that spiralled completely out of control?" },
  { category: "Embarrassing & Cringe", question: "What's the worst place to trip and fall?" },
  { category: "Embarrassing & Cringe", question: "What's an embarrassing nickname you've been stuck with?" },
  { category: "Embarrassing & Cringe", question: "What's the cringiest thing to shout in public?" },
  { category: "Embarrassing & Cringe", question: "What's a habit you'd never admit on a first date?" },
  { category: "Embarrassing & Cringe", question: "What's the worst time to get caught talking to yourself?" },
  { category: "Embarrassing & Cringe", question: "What's an embarrassing thing parents do in public?" },
  { category: "Embarrassing & Cringe", question: "What's the most awkward thing to happen in a meeting?" },
  { category: "Embarrassing & Cringe", question: "What's a fashion choice from your past you deeply regret?" },
  { category: "Embarrassing & Cringe", question: "What's the worst thing to call a teacher by accident?" },
  { category: "Embarrassing & Cringe", question: "What's an embarrassing reason you've cried?" },
  { category: "Embarrassing & Cringe", question: "What's the most awkward lift moment?" },
  { category: "Embarrassing & Cringe", question: "What's a secret talent that's actually embarrassing?" },
  { category: "Embarrassing & Cringe", question: "Who's the worst person to forget the name of?" },
  { category: "Embarrassing & Cringe", question: "What's an embarrassing thing to be caught singing?" },
  { category: "Embarrassing & Cringe", question: "What's the cringiest type of social media post?" },
  { category: "Embarrassing & Cringe", question: "What's the worst autocorrect fail you've sent?" },
  { category: "Embarrassing & Cringe", question: "What's an embarrassing childhood obsession?" },
  { category: "Embarrassing & Cringe", question: "What's the most awkward thing to do on a first date?" },
  { category: "Embarrassing & Cringe", question: "What's a moment that still haunts you at 3am?" },
  { category: "Embarrassing & Cringe", question: "What's the worst time for your stomach to growl loudly?" },
  { category: "Embarrassing & Cringe", question: "What's an embarrassing thing to become famous for?" },
  { category: "Embarrassing & Cringe", question: "What's the cringiest pickup line you've heard?" },
  { category: "Embarrassing & Cringe", question: "What's the worst reason to wave back at a stranger?" },
  { category: "Embarrassing & Cringe", question: "What's an embarrassing thing in everyone's photo gallery?" },
  { category: "Embarrassing & Cringe", question: "What's the most awkward family WhatsApp group moment?" },
  { category: "Embarrassing & Cringe", question: "What's a thing you pretend to understand but don't?" },
  { category: "Embarrassing & Cringe", question: "What's the worst place to get the giggles?" },
  { category: "Embarrassing & Cringe", question: "What's an embarrassing thing to be passionate about?" },
  { category: "Embarrassing & Cringe", question: "What's the cringiest thing you've overheard yourself say?" },
  { category: "Embarrassing & Cringe", question: "What's the worst dance move to bust out sober?" },
  { category: "Embarrassing & Cringe", question: "What's an embarrassing excuse you've used for being late?" },
  { category: "Embarrassing & Cringe", question: "What's the most awkward compliment to receive?" },
  { category: "Embarrassing & Cringe", question: "What's a phase everyone's embarrassed they had?" },
  { category: "Embarrassing & Cringe", question: "What's the worst thing to spill on yourself before an event?" },
  { category: "Embarrassing & Cringe", question: "What's an embarrassing thing to get excited about as an adult?" },
  { category: "Embarrassing & Cringe", question: "What's the cringiest thing to do at a concert?" },
  { category: "Embarrassing & Cringe", question: "What's the worst time to realise you have food in your teeth?" },
  { category: "Embarrassing & Cringe", question: "What's an embarrassing thing to be terrible at?" },
  { category: "Embarrassing & Cringe", question: "What's the most awkward goodbye situation?" },
  { category: "Embarrassing & Cringe", question: "What's a thing you've Googled at 2am and regretted?" },
  { category: "Embarrassing & Cringe", question: "What's the worst moment to start laughing?" },
  { category: "Embarrassing & Cringe", question: "What's an embarrassing thing to cry during?" },
  { category: "Embarrassing & Cringe", question: "What's the cringiest abbreviation people text?" },
  { category: "Embarrassing & Cringe", question: "What's the worst daydream to get caught having?" },

  // ===== Family & Relatives =====
  { category: "Family & Relatives", question: "What's the most annoying question relatives always ask?" },
  { category: "Family & Relatives", question: "What's a thing every mom keeps 'for guests'?" },
  { category: "Family & Relatives", question: "What's the worst comparison relatives make?" },
  { category: "Family & Relatives", question: "What's a chore your parents nag you about endlessly?" },
  { category: "Family & Relatives", question: "What's the most dramatic thing an aunty has said?" },
  { category: "Family & Relatives", question: "What's a thing every dad does with the fan or AC?" },
  { category: "Family & Relatives", question: "What's the worst seat at a family function?" },
  { category: "Family & Relatives", question: "What's a thing relatives judge you for instantly?" },
  { category: "Family & Relatives", question: "What's the most overused parental threat?" },
  { category: "Family & Relatives", question: "What's a thing your mom says right before guests arrive?" },
  { category: "Family & Relatives", question: "What's the worst time for a relative to call?" },
  { category: "Family & Relatives", question: "What's a thing every household hoards forever?" },
  { category: "Family & Relatives", question: "What's the most awkward dinner-table topic?" },
  { category: "Family & Relatives", question: "What's a thing parents brag about to other parents?" },
  { category: "Family & Relatives", question: "What's the worst gift a relative has given you?" },
  { category: "Family & Relatives", question: "What's a thing aunties gossip about at every function?" },
  { category: "Family & Relatives", question: "What's the most unrealistic expectation parents have?" },
  { category: "Family & Relatives", question: "What's a thing your dad refuses to throw away?" },
  { category: "Family & Relatives", question: "What's the worst advice from a relative?" },
  { category: "Family & Relatives", question: "What's a thing every family WhatsApp group sends daily?" },
  { category: "Family & Relatives", question: "What's the most chaotic part of a family wedding?" },
  { category: "Family & Relatives", question: "What's a thing relatives always exaggerate?" },
  { category: "Family & Relatives", question: "What's a thing parents say that makes no sense?" },
  { category: "Family & Relatives", question: "What's the most competitive thing between cousins?" },
  { category: "Family & Relatives", question: "What's a thing your mom blames for everything?" },
  { category: "Family & Relatives", question: "What's the worst part of visiting relatives?" },
  { category: "Family & Relatives", question: "What's a thing every grandparent says?" },
  { category: "Family & Relatives", question: "What's the most over-the-top thing at a wedding?" },
  { category: "Family & Relatives", question: "What's a thing parents do that embarrasses you?" },
  { category: "Family & Relatives", question: "What's the worst 'log kya kahenge' moment?" },
  { category: "Family & Relatives", question: "What's a thing relatives never let you forget?" },
  { category: "Family & Relatives", question: "What's the most annoying festival chore?" },
  { category: "Family & Relatives", question: "What's a thing your family does at every gathering?" },
  { category: "Family & Relatives", question: "What's the worst thing to admit to your parents?" },
  { category: "Family & Relatives", question: "What's a thing aunties always comment on?" },
  { category: "Family & Relatives", question: "What's the most predictable relative reaction?" },
  { category: "Family & Relatives", question: "What's a thing parents do with leftover food?" },
  { category: "Family & Relatives", question: "What's the worst part of a 3-day wedding?" },
  { category: "Family & Relatives", question: "What's a thing every dad is weirdly proud of?" },
  { category: "Family & Relatives", question: "What's the most awkward thing at a family reunion?" },
  { category: "Family & Relatives", question: "What's a thing your mom refuses to learn on the phone?" },
  { category: "Family & Relatives", question: "What's the worst guest behaviour at a function?" },
  { category: "Family & Relatives", question: "What's a thing parents say about your sleep schedule?" },
  { category: "Family & Relatives", question: "What's the most dramatic family argument topic?" },
  { category: "Family & Relatives", question: "What's a thing relatives always overpack?" },
  { category: "Family & Relatives", question: "What's the worst thing to be woken up for?" },
  { category: "Family & Relatives", question: "What's a thing every household saves 'for later'?" },
  { category: "Family & Relatives", question: "What's the most annoying thing about a shared family car?" },
  { category: "Family & Relatives", question: "What's a thing your parents do that you'll definitely do too?" },
  { category: "Family & Relatives", question: "What's the worst thing to interrupt your dad's nap for?" },

  // ===== Food & Cravings =====
  { category: "Food & Cravings", question: "What's the most overrated street food?" },
  { category: "Food & Cravings", question: "What's a food combo that sounds gross but works?" },
  { category: "Food & Cravings", question: "What's the worst pizza topping?" },
  { category: "Food & Cravings", question: "What's a snack you physically cannot stop eating?" },
  { category: "Food & Cravings", question: "What's the most overrated restaurant trend?" },
  { category: "Food & Cravings", question: "What's the worst thing to put in Maggi?" },
  { category: "Food & Cravings", question: "What food could you eat for breakfast, lunch and dinner?" },
  { category: "Food & Cravings", question: "What's the most disappointing mithai?" },
  { category: "Food & Cravings", question: "What's the worst flavour of ice cream?" },
  { category: "Food & Cravings", question: "What's a comfort food that hits at 2am?" },
  { category: "Food & Cravings", question: "What's the most overrated coffee order?" },
  { category: "Food & Cravings", question: "What's a dish everyone loves but you secretly hate?" },
  { category: "Food & Cravings", question: "What's the worst thing to order on a first date?" },
  { category: "Food & Cravings", question: "What's a guilty-pleasure junk food?" },
  { category: "Food & Cravings", question: "What's the most pointless 'healthy' food?" },
  { category: "Food & Cravings", question: "What's the worst chaat to mess up?" },
  { category: "Food & Cravings", question: "What's a food that's only good when someone else makes it?" },
  { category: "Food & Cravings", question: "What's the most overrated cuisine?" },
  { category: "Food & Cravings", question: "What's the worst topping on a dosa?" },
  { category: "Food & Cravings", question: "What's a snack that's basically a personality?" },
  { category: "Food & Cravings", question: "What's the most overrated chocolate?" },
  { category: "Food & Cravings", question: "What's the worst thing to run out of mid-recipe?" },
  { category: "Food & Cravings", question: "What's a food you eat in a weird way?" },
  { category: "Food & Cravings", question: "What's the most disappointing birthday cake flavour?" },
  { category: "Food & Cravings", question: "What's the worst thing to bring to a potluck?" },
  { category: "Food & Cravings", question: "What's a drink that's way too sweet?" },
  { category: "Food & Cravings", question: "What's the most overrated breakfast?" },
  { category: "Food & Cravings", question: "What's the worst leftover to reheat?" },
  { category: "Food & Cravings", question: "What's a food worth the bad breath?" },
  { category: "Food & Cravings", question: "What's the most overrated 'fancy' dish?" },
  { category: "Food & Cravings", question: "What's the worst thing to dip in chutney?" },
  { category: "Food & Cravings", question: "What's a snack you'd hide from your flatmates?" },
  { category: "Food & Cravings", question: "What's the most overrated festival sweet?" },
  { category: "Food & Cravings", question: "What's the worst thing to microwave in an office?" },
  { category: "Food & Cravings", question: "What's a food that smells better than it tastes?" },
  { category: "Food & Cravings", question: "What's the most overrated fruit?" },
  { category: "Food & Cravings", question: "What's the worst thing to put on a paratha?" },
  { category: "Food & Cravings", question: "What's a craving that always hits at the worst time?" },
  { category: "Food & Cravings", question: "What's the most disappointing free sample?" },
  { category: "Food & Cravings", question: "What's the worst biryani crime?" },
  { category: "Food & Cravings", question: "What's a food you'd fight for the last bite of?" },
  { category: "Food & Cravings", question: "What's the most overrated viral food?" },
  { category: "Food & Cravings", question: "What's the worst thing to order at the movies?" },
  { category: "Food & Cravings", question: "What's a food that's all hype?" },
  { category: "Food & Cravings", question: "What's the worst packet snack?" },
  { category: "Food & Cravings", question: "What's a dish that vanishes the second it's served?" },
  { category: "Food & Cravings", question: "What's the most overrated takeaway?" },
  { category: "Food & Cravings", question: "What's the worst thing to find at the bottom of the packet?" },
  { category: "Food & Cravings", question: "What's a food you pretend to like to be polite?" },
  { category: "Food & Cravings", question: "What's the worst pizza-and-topping combo ever?" },

  // ===== Dating & Relationships =====
  { category: "Dating & Relationships", question: "What's the biggest red flag on a first date?" },
  { category: "Dating & Relationships", question: "What's the worst place to break up with someone?" },
  { category: "Dating & Relationships", question: "What's a green flag people underrate?" },
  { category: "Dating & Relationships", question: "What's the most overrated romantic gesture?" },
  { category: "Dating & Relationships", question: "What's the worst pet name for a partner?" },
  { category: "Dating & Relationships", question: "What's a dealbreaker that's secretly petty?" },
  { category: "Dating & Relationships", question: "What's the worst thing to discover on a date?" },
  { category: "Dating & Relationships", question: "What's the most unrealistic relationship in movies?" },
  { category: "Dating & Relationships", question: "What's a terrible idea for a first date?" },
  { category: "Dating & Relationships", question: "What's the worst gift for a new partner?" },
  { category: "Dating & Relationships", question: "What's a lie everyone tells on dating apps?" },
  { category: "Dating & Relationships", question: "What's the cringiest way to slide into DMs?" },
  { category: "Dating & Relationships", question: "What's the worst time to say 'I love you'?" },
  { category: "Dating & Relationships", question: "What's an overrated quality people look for?" },
  { category: "Dating & Relationships", question: "What's the pettiest reason to end things?" },
  { category: "Dating & Relationships", question: "What's the worst thing to text after a date?" },
  { category: "Dating & Relationships", question: "What's a couple habit that's secretly annoying?" },
  { category: "Dating & Relationships", question: "What's the most awkward 'meet the parents' moment?" },
  { category: "Dating & Relationships", question: "What's the worst couple costume?" },
  { category: "Dating & Relationships", question: "What's a romantic trope that's actually creepy?" },
  { category: "Dating & Relationships", question: "What's the worst place to propose?" },
  { category: "Dating & Relationships", question: "What's a thing couples fight about that's so dumb?" },
  { category: "Dating & Relationships", question: "What's the worst dating app bio?" },
  { category: "Dating & Relationships", question: "What's an ick that's totally unreasonable?" },
  { category: "Dating & Relationships", question: "What's the worst thing to lie about to a partner?" },
  { category: "Dating & Relationships", question: "What's the most overrated date idea?" },
  { category: "Dating & Relationships", question: "What's a thing single people always lie about?" },
  { category: "Dating & Relationships", question: "What's the worst way to find out you've been ghosted?" },
  { category: "Dating & Relationships", question: "What's the cringiest thing couples do in public?" },
  { category: "Dating & Relationships", question: "What's the worst time for your phone to buzz on a date?" },
  { category: "Dating & Relationships", question: "What's a thing everyone does after a breakup?" },
  { category: "Dating & Relationships", question: "What's the worst place to cry over an ex?" },
  { category: "Dating & Relationships", question: "What's an overrated love song?" },
  { category: "Dating & Relationships", question: "What's the most unrealistic dating advice?" },
  { category: "Dating & Relationships", question: "What's a red flag people ignore for looks?" },
  { category: "Dating & Relationships", question: "What's the worst thing to find on a partner's phone?" },
  { category: "Dating & Relationships", question: "What's the cringiest anniversary gift?" },
  { category: "Dating & Relationships", question: "What's the worst third-wheel situation?" },
  { category: "Dating & Relationships", question: "What's a thing long-term couples stop pretending about?" },
  { category: "Dating & Relationships", question: "What's the worst time to bring up your ex?" },
  { category: "Dating & Relationships", question: "What's an overrated honeymoon destination?" },
  { category: "Dating & Relationships", question: "What's the worst way to flirt?" },
  { category: "Dating & Relationships", question: "What's a thing that kills the mood instantly?" },
  { category: "Dating & Relationships", question: "What's the most awkward double-date scenario?" },
  { category: "Dating & Relationships", question: "What's the worst thing to whisper on a first date?" },
  { category: "Dating & Relationships", question: "What's an underrated romantic gesture?" },
  { category: "Dating & Relationships", question: "What's the worst reason to stay with someone?" },
  { category: "Dating & Relationships", question: "What's the most overrated 'couple goal'?" },
  { category: "Dating & Relationships", question: "What's the worst thing for a partner to be bad at?" },
  { category: "Dating & Relationships", question: "What's the cringiest relationship social media post?" },

  // ===== Money, Work & Adulting =====
  { category: "Money, Work & Adulting", question: "What's the worst thing to blow your salary on?" },
  { category: "Money, Work & Adulting", question: "What's a job that sounds fun but would be hell?" },
  { category: "Money, Work & Adulting", question: "What's the most pointless meeting topic?" },
  { category: "Money, Work & Adulting", question: "What's the worst excuse for being late to work?" },
  { category: "Money, Work & Adulting", question: "What's a purchase you regretted instantly?" },
  { category: "Money, Work & Adulting", question: "What's the worst boss habit?" },
  { category: "Money, Work & Adulting", question: "What's a thing adults waste money on?" },
  { category: "Money, Work & Adulting", question: "What's the worst way to quit a job?" },
  { category: "Money, Work & Adulting", question: "What's the most annoying type of coworker?" },
  { category: "Money, Work & Adulting", question: "What's the first thing you'd buy if you won the lottery?" },
  { category: "Money, Work & Adulting", question: "What's the worst place to take a work call?" },
  { category: "Money, Work & Adulting", question: "What's an adult task nobody warns you about?" },
  { category: "Money, Work & Adulting", question: "What's the worst thing to say in a job interview?" },
  { category: "Money, Work & Adulting", question: "What's the most overrated career?" },
  { category: "Money, Work & Adulting", question: "What's a subscription everyone forgets they pay for?" },
  { category: "Money, Work & Adulting", question: "What's the worst office party activity?" },
  { category: "Money, Work & Adulting", question: "What's a thing that's a rip-off but we all pay for?" },
  { category: "Money, Work & Adulting", question: "What's the worst time for the WiFi to die?" },
  { category: "Money, Work & Adulting", question: "What's an adulting skill everyone fakes?" },
  { category: "Money, Work & Adulting", question: "What's the worst thing to find in the office fridge?" },
  { category: "Money, Work & Adulting", question: "What's the most useless office gadget?" },
  { category: "Money, Work & Adulting", question: "What's the worst reply-all email moment?" },
  { category: "Money, Work & Adulting", question: "What's an overrated luxury?" },
  { category: "Money, Work & Adulting", question: "What's the worst way to find out you're fired?" },
  { category: "Money, Work & Adulting", question: "What's a thing that costs way too much now?" },
  { category: "Money, Work & Adulting", question: "What's the most cringe LinkedIn post?" },
  { category: "Money, Work & Adulting", question: "What's the worst thing to be put in charge of?" },
  { category: "Money, Work & Adulting", question: "What's a chore you'd happily pay to never do?" },
  { category: "Money, Work & Adulting", question: "What's the worst meeting time slot?" },
  { category: "Money, Work & Adulting", question: "What's a sign someone's bad with money?" },
  { category: "Money, Work & Adulting", question: "What's the worst 'team building' activity?" },
  { category: "Money, Work & Adulting", question: "What's the most pointless adult purchase?" },
  { category: "Money, Work & Adulting", question: "What's the worst thing to forget before a deadline?" },
  { category: "Money, Work & Adulting", question: "What's a thing everyone exaggerates on their resume?" },
  { category: "Money, Work & Adulting", question: "What's the worst commute situation?" },
  { category: "Money, Work & Adulting", question: "What's an overrated productivity hack?" },
  { category: "Money, Work & Adulting", question: "What's the worst place to work from?" },
  { category: "Money, Work & Adulting", question: "What's a thing that breaks right after the warranty ends?" },
  { category: "Money, Work & Adulting", question: "What's the worst icebreaker at a work event?" },
  { category: "Money, Work & Adulting", question: "What's a thing you'd splurge on with zero regret?" },
  { category: "Money, Work & Adulting", question: "What's the most annoying autopay surprise?" },
  { category: "Money, Work & Adulting", question: "What's the worst thing to say to your landlord?" },
  { category: "Money, Work & Adulting", question: "What's a job you'd be hilariously bad at?" },
  { category: "Money, Work & Adulting", question: "What's the worst time to run out of money?" },
  { category: "Money, Work & Adulting", question: "What's an overrated status symbol?" },
  { category: "Money, Work & Adulting", question: "What's the worst thing to put on an expense report?" },
  { category: "Money, Work & Adulting", question: "What's a thing nobody admits they can't afford?" },
  { category: "Money, Work & Adulting", question: "What's the worst desk-neighbour habit?" },
  { category: "Money, Work & Adulting", question: "What's the worst way to spend a sick day?" },
  { category: "Money, Work & Adulting", question: "What's the most overrated 'side hustle'?" },

  // ===== Hypotheticals & Superpowers =====
  { category: "Hypotheticals & Superpowers", question: "What superpower would be useless in real life?" },
  { category: "Hypotheticals & Superpowers", question: "What animal would make the worst pet?" },
  { category: "Hypotheticals & Superpowers", question: "If you were invisible for a day, where would you sneak into?" },
  { category: "Hypotheticals & Superpowers", question: "What would you do with one extra hour every day?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst superpower to have at a funeral?" },
  { category: "Hypotheticals & Superpowers", question: "Which two animals would you pay to watch fight?" },
  { category: "Hypotheticals & Superpowers", question: "What would you ban if you ruled the world for a day?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst place to be teleported randomly?" },
  { category: "Hypotheticals & Superpowers", question: "What food could you never give up?" },
  { category: "Hypotheticals & Superpowers", question: "What's a useless skill you'd love to master?" },
  { category: "Hypotheticals & Superpowers", question: "What would you do first if you woke up famous?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst way to discover you're immortal?" },
  { category: "Hypotheticals & Superpowers", question: "If animals could talk, which would be the rudest?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst superpower for a villain?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst era to be stuck in?" },
  { category: "Hypotheticals & Superpowers", question: "Whose life would you NOT want to swap for a day?" },
  { category: "Hypotheticals & Superpowers", question: "What's a law you'd secretly love to break?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst thing to be reincarnated as?" },
  { category: "Hypotheticals & Superpowers", question: "If you had a clone, what chore would you dump on it?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst place to have super hearing?" },
  { category: "Hypotheticals & Superpowers", question: "What would you do with the power to pause time?" },
  { category: "Hypotheticals & Superpowers", question: "What's the most pointless thing to be world champion at?" },
  { category: "Hypotheticals & Superpowers", question: "If you could read minds, whose would you avoid?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst gift a genie could give?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst animal to be the size of a dog?" },
  { category: "Hypotheticals & Superpowers", question: "If you could teleport, what would you stop doing?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst thing to be able to predict?" },
  { category: "Hypotheticals & Superpowers", question: "What would you do with unlimited money for one day?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst superpower to have on a date?" },
  { category: "Hypotheticals & Superpowers", question: "If you ruled a tiny country, what's your first law?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst talent to go viral for?" },
  { category: "Hypotheticals & Superpowers", question: "What would you do if you could never sleep again?" },
  { category: "Hypotheticals & Superpowers", question: "If you could talk to one animal, which is a bad idea?" },
  { category: "Hypotheticals & Superpowers", question: "What's the most useless thing to be immortal for?" },
  { category: "Hypotheticals & Superpowers", question: "What would you do if everyone could hear your thoughts?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst superhero name?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst thing to be allergic to?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst era to time-travel to as yourself?" },
  { category: "Hypotheticals & Superpowers", question: "If you wore one outfit forever, what would you avoid?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst thing to be the world's best at?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst place to have a teleport accident?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst wish to make to a genie?" },
  { category: "Hypotheticals & Superpowers", question: "If you could shrink anything, what would you misuse it on?" },
  { category: "Hypotheticals & Superpowers", question: "What would you do if gravity switched off for a minute?" },
  { category: "Hypotheticals & Superpowers", question: "If you could swap voices with anyone, who's a bad pick?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst thing to be able to summon at will?" },
  { category: "Hypotheticals & Superpowers", question: "What would you do with a day nobody else remembers?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst superpower to give a toddler?" },
  { category: "Hypotheticals & Superpowers", question: "If you had to be famous for one thing, what would you avoid?" },
  { category: "Hypotheticals & Superpowers", question: "What's the worst thing to be able to read minds about?" },

  // ===== Dark Comedy =====
  { category: "Dark Comedy", question: "What's a terrible thing to say at a funeral?" },
  { category: "Dark Comedy", question: "What's the worst-possible last meal?" },
  { category: "Dark Comedy", question: "Where's the worst place to faint?" },
  { category: "Dark Comedy", question: "What's a lie everyone tells the doctor?" },
  { category: "Dark Comedy", question: "What would you regret buying on EMI?" },
  { category: "Dark Comedy", question: "What's the worst gift to give at a wedding?" },
  { category: "Dark Comedy", question: "Who's the worst person to be stuck in a lift with?" },
  { category: "Dark Comedy", question: "When's the worst time for your phone to die?" },
  { category: "Dark Comedy", question: "What's a terrible excuse for missing a funeral?" },
  { category: "Dark Comedy", question: "What would you want buried with you?" },
  { category: "Dark Comedy", question: "What's a terrible name for a hospital?" },
  { category: "Dark Comedy", question: "What's the worst thing to find in your biryani?" },
  { category: "Dark Comedy", question: "What always dies at the worst possible moment?" },
  { category: "Dark Comedy", question: "What's the worst job for a clumsy person?" },
  { category: "Dark Comedy", question: "What's a terrible theme for a birthday party?" },
  { category: "Dark Comedy", question: "When's the worst time to start laughing?" },
  { category: "Dark Comedy", question: "What would you fake your death to avoid?" },
  { category: "Dark Comedy", question: "Which pet is a terrible idea in a small flat?" },
  { category: "Dark Comedy", question: "What's the worst thing to forget on your wedding day?" },
  { category: "Dark Comedy", question: "What's the worst song to play at a funeral?" },
  { category: "Dark Comedy", question: "What always ruins a group photo?" },
  { category: "Dark Comedy", question: "Where's the worst place to lose your wallet?" },
  { category: "Dark Comedy", question: "What's a doomed new year resolution?" },
  { category: "Dark Comedy", question: "When's the worst time to run out of toilet paper?" },
  { category: "Dark Comedy", question: "Which is the worst seat on a long flight?" },
  { category: "Dark Comedy", question: "What does nobody admit they Google?" },
  { category: "Dark Comedy", question: "What's the worst nickname to be stuck with?" },
  { category: "Dark Comedy", question: "What's a terrible excuse for being late to your own wedding?" },
  { category: "Dark Comedy", question: "What's the worst thing to whisper in the dark?" },
  { category: "Dark Comedy", question: "What's a terrible gift for a newborn?" },
  { category: "Dark Comedy", question: "Where's the worst place to get a call from your boss?" },
  { category: "Dark Comedy", question: "What always breaks right after the warranty ends?" },
  { category: "Dark Comedy", question: "When's the worst time to sneeze?" },
  { category: "Dark Comedy", question: "What's a terrible password everyone has used?" },
  { category: "Dark Comedy", question: "What's the worst roommate habit?" },
  { category: "Dark Comedy", question: "What should you never say to a traffic cop?" },
  { category: "Dark Comedy", question: "Where's the worst place to get hiccups?" },
  { category: "Dark Comedy", question: "What would you hate to inherit?" },
  { category: "Dark Comedy", question: "What's the worst reason to become famous?" },
  { category: "Dark Comedy", question: "What's a terrible thing to be allergic to?" },
  { category: "Dark Comedy", question: "When's the worst time for the WiFi to die?" },
  { category: "Dark Comedy", question: "What's the worst thing to find in the office fridge?" },
  { category: "Dark Comedy", question: "What's the worst way to find out you're fired?" },
  { category: "Dark Comedy", question: "What still haunts you from your school days?" },
  { category: "Dark Comedy", question: "What's the worst way to break up with someone?" },
  { category: "Dark Comedy", question: "Who's the worst plus-one for a date?" },
  { category: "Dark Comedy", question: "What's a slow death disguised as a family function?" },
  { category: "Dark Comedy", question: "What's the worst superpower to have at a funeral?" },
  { category: "Dark Comedy", question: "What's the worst flavour of ice cream?" },
  { category: "Dark Comedy", question: "What's the worst job to be doing at 3am?" },

  // ===== The Group =====
  { category: "The Group", question: "Who in this group is always late?" },
  { category: "The Group", question: "Who here gives the best advice?" },
  { category: "The Group", question: "Who'd survive longest on a deserted island?" },
  { category: "The Group", question: "Who could write a bestselling memoir?" },
  { category: "The Group", question: "Who's most likely to go off-grid for a month?" },
  { category: "The Group", question: "Who talks the most in this group?" },
  { category: "The Group", question: "Who's the unofficial parent of this group?" },
  { category: "The Group", question: "Who'd win a debate about literally anything?" },
  { category: "The Group", question: "Who's most likely to become famous?" },
  { category: "The Group", question: "Who's the most competitive person here?" },
  { category: "The Group", question: "Who's most likely to plan the next trip?" },
  { category: "The Group", question: "Who'd forget their own birthday?" },
  { category: "The Group", question: "Who has the most screenshots saved?" },
  { category: "The Group", question: "Who's most likely to cry at a movie?" },
  { category: "The Group", question: "Who'd survive a zombie apocalypse?" },
  { category: "The Group", question: "Who's the worst at replying to texts?" },
  { category: "The Group", question: "Who's most likely to start a podcast?" },
  { category: "The Group", question: "Who'd accidentally join a cult?" },
  { category: "The Group", question: "Who takes the most photos of their food?" },
  { category: "The Group", question: "Who's most likely to fall asleep first at a party?" },
  { category: "The Group", question: "Who'd spend their whole salary in a day?" },
  { category: "The Group", question: "Who's the most dramatic?" },
  { category: "The Group", question: "Who'd get lost in their own neighbourhood?" },
  { category: "The Group", question: "Who's most likely to ghost the group chat?" },
  { category: "The Group", question: "Who'd adopt 10 pets if they could?" },
];

// Unique category list, in first-seen order — handy for a future category filter / picker.
export const CATEGORIES = [...new Set(QUESTIONS.map((q) => q.category))];
